### ISSUE TITLE
touchscreen not working on sp4

### ISSUE THREAD

**Issue by raspbeguy** [linux-surface/linux-surface#313]
Maybe I'm missing something, but I can't make touchscreen work on my Surface Pro 4.
I would gladly share a dmesg excerpt but I just don't know what part of it is interresting.

### Environment

- Hardware model: Surface Pro 4
- Kernel version: 5.9.1-arch1-1-surface #1 SMP PREEMPT Thu, 22 Oct 2020 16:57:47 +0000 x86_64 GNU/Linux
- Distribution: Arch Linux

**Comment by StollD** [comment]
I messed up the iptsd release. The daemon itself works fine, but systemd will refuse to start it because it is waiting for a device file that doesn't exist anymore.

I tagged a new iptsd release that fixes this about 30 minutes ago, and it should already be in the repositories (iptsd 0.2.1). Can you please update to that and see if that fixes your issue?

**Comment by Ivoo25** [comment]
> I messed up the iptsd release. The daemon itself works fine, but systemd will refuse to start it because it is waiting for a device file that doesn't exist anymore.
> 
> I tagged a new iptsd release that fixes this about 30 minutes ago, and it should already be in the repositories (iptsd 0.2.1). Can you please update to that and see if that fixes your issue?

Could you please handle me the link for that? I have the same issue on sp6

**Comment by thisisnotmyuserid** [comment]
I am also on a SB4 and having the same issue.
kernel: Linux Surface 5.9.1-surface #1 SMP Thu Oct 22 17:00:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Distro: Mint 20

I do have iptsd at 0.2.1-1, and I have the same issue still unfortunately.

**Comment by raspbeguy** [comment]
@StollD sorry for late response, I became father meanwhile.
So it still doesn't seem to work. I've git this message when running iptsd:
```
no such device
main.ioctl
	/home/raspbeguy/repo/iptsd-0.2.1/ioctl.go:13
main.(*IptsControl).SendFeedbackFile
	/home/raspbeguy/repo/iptsd-0.2.1/control.go:156
main.(*IptsControl).Flush
	/home/raspbeguy/repo/iptsd-0.2.1/control.go:181
main.(*IptsControl).Start
	/home/raspbeguy/repo/iptsd-0.2.1/control.go:57
main.main
	/home/raspbeguy/repo/iptsd-0.2.1/main.go:46
runtime.main
	/usr/lib/go/src/runtime/proc.go:204
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1374
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4fc629]

goroutine 1 [running]:
main.(*IptsDevices).Destroy(0xc00006c2d0, 0xc000206000, 0x0)
	/home/raspbeguy/repo/iptsd-0.2.1/devices.go:191 +0x29
main.Shutdown(0xc00006c2a0)
	/home/raspbeguy/repo/iptsd-0.2.1/main.go:22 +0x2f
main.HandleError(0xc00006c2a0, 0x55b4c0, 0xc000204020)
	/home/raspbeguy/repo/iptsd-0.2.1/main.go:29 +0xa5
main.main()
	/home/raspbeguy/repo/iptsd-0.2.1/main.go:48 +0x7e5
```

**Comment by David-OConnor** [comment]
I'm unable to get the touchsccreen or pen working on SP2017. Could this be the same issue?

**Comment by raspbeguy** [comment]
Friendly ping :)

**Comment by StollD** [comment]
Sorry, totally looked over this. Could you please post your dmesg?

Also, could you try the iptsd master branch? We rewrote the daemon in C and did a lot of improvements, so I would be curious if we accidentally fixed the issue without knowing.

**Comment by mknw** [comment]
Same on sp5, still care about dmesg?

**Comment by StollD** [comment]
@mknw Sure! But since there was an iptsd release recently with pretty substantial changes, please don't just post dmesg, but the full journal log (`journalctl -b`). Also make sure you are on the latest version of iptsd (0.3.1).

**Comment by mknw** [comment]
@StollD thanks for your reply. I actually managed to get it to work by installing the new version of iptsd. :)

**Comment by raspbeguy** [comment]
@StollD sorry for the delay, I had to get back my SP4 to test.

Still not working.

```
➜  ~ sudo dmesg | grep ipts
[   14.295996] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Starting IPTS
[   19.778704] audit: type=1131 audit(1609877218.109:63): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=iptsd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
➜  ~ sudo iptsd            
ERROR: ../src/control.c:52: Failed to send feedback: No such device
ERROR: ../src/control.c:75: Failed to flush buffers: No such device
ERROR: ../src/main.c:83: Failed to start IPTS: No such device
➜  ~ uname -r
5.10.2-arch1-1-surface
```
iptsd is the latest archlinux version.

**Comment by StollD** [comment]
You need to post the full dmesg. Errors dont neccessarily respect grep patterns.

**Comment by raspbeguy** [comment]
@StollD I sent it to you by email, because I'm not ok with giving a dmesg output on a public place.

**Comment by StollD** [comment]
@raspbeguy Thanks for the dmesg! I see in your log that you have `intel_iommu` enabled. Doing that, for some reason, disables IPTS. You need to remove the iommu related settings from the kernel commandline for ipts to start properly. 

I speculated a bit about this in the past in https://github.com/linux-surface/intel-precise-touch/issues/3, but this is the first time I am actually seeing a dmesg from the problem, and there is an error message that I will look into.

```
[   12.344802] DMAR: DRHD: handling fault status reg 2
[   12.344808] DMAR: [DMA Read] Request device [00:16.4] PASID ffffffff fault addr 133a5f000 [fault reason 06] PTE Read access is not set
```

**Comment by raspbeguy** [comment]
Fantastic, now it works !
Thanks a lot.
