### ISSUE TITLE
[SLS] Support for Surface Aggregator Module (Keyboard, Touchpad, Battery)

### ISSUE THREAD

**Issue by qzed** [linux-surface/linux-surface#596]
Add support for Surface Aggregator Module (SAM) subsystem devices on the Surface Laptop Studio. This seems to be the usual straight-forward addition of IDs to the registry. SAM probes correctly and seems to be accessible, although there is a warning that DMA could not be requested.

Full diagnostics package: https://github.com/linux-surface/acpidumps/files/7316139/diagnostics.tar.gz

**Comment by qzed** [comment]
@ukasuviok Can you clone https://github.com/linux-surface/surface-aggregator-module and run the following commands (from inside the cloned repository)?

First run `sudo modprobe surface_aggregator_cdev`, then

```sh
sudo ./scripts/ssam/hid.py hid-get-descriptor 1 1    # should be keyboard
sudo ./scripts/ssam/hid.py hid-get-descriptor 2 1
sudo ./scripts/ssam/hid.py hid-get-descriptor 3 1    # should be touchpad
sudo ./scripts/ssam/hid.py hid-get-descriptor 4 1
sudo ./scripts/ssam/hid.py hid-get-descriptor 5 1
sudo ./scripts/ssam/hid.py hid-get-descriptor 6 1
sudo ./scripts/ssam/hid.py hid-get-descriptor 7 1
sudo ./scripts/ssam/hid.py hid-get-descriptor 8 1
sudo ./scripts/ssam/hid.py hid-get-descriptor 9 1
```

and post the outputs of those commands. This helps us identify which HID devices are connected and which devices we need to add to the registry. Finally run

```sh
sudo ./scripts/ssam/ctrl.py request 2 1 1 0 1
sudo ./scripts/ssam/ctrl.py request 2 1 1 1 1
sudo ./scripts/ssam/ctrl.py request 2 2 1 0 1
sudo ./scripts/ssam/ctrl.py request 2 2 1 1 1
```

and also post the output of that. This should help verify that the battery interface hasn't changed.

**Comment by ukasuviok** [comment]
I cloned the repository, but ssam/hid.py doesn't exist.

**Comment by ukasuviok** [comment]
All of the hid.py commands fail with the following error:

Traceback (most recent call last):
  File "/home/ukas/surface-aggregator-module/./scripts/ssam/hid.py", line 132, in <module>
    main()
  File "/home/ukas/surface-aggregator-module/./scripts/ssam/hid.py", line 124, in main
    dump_raw_data(dev.get_device_descriptor(entry))
  File "/home/ukas/surface-aggregator-module/./scripts/ssam/hid.py", line 47, in get_device_descriptor
    done, part = self._get_device_descriptor_part(entry, len(data), n)
  File "/home/ukas/surface-aggregator-module/./scripts/ssam/hid.py", line 57, in _get_device_descriptor_part
    resp = self.ctrl.request(rqst)
  File "/home/ukas/surface-aggregator-module/scripts/ssam/libssam.py", line 350, in request
    return _request(self.fd, request)
  File "/home/ukas/surface-aggregator-module/scripts/ssam/libssam.py", line 258, in _request
    raise OSError(-raw.status, errno.errorcode.get(-raw.status))
TimeoutError: [Errno 110] ETIMEDOUT

Output of the ctrl.py commands below:
sudo ./scripts/ssam/ctrl.py request 2 1 1 0 1
1f 00 00 00

sudo ./scripts/ssam/ctrl.py request 2 1 1 1 1
1f 00 00 00

sudo ./scripts/ssam/ctrl.py request 2 2 1 0 1
Traceback (most recent call last):
  File "/home/ukas/surface-aggregator-module/./scripts/ssam/ctrl.py", line 49, in <module>
    main()
  File "/home/ukas/surface-aggregator-module/./scripts/ssam/ctrl.py", line 43, in main
    rsp = ctrl.request(rqst)
  File "/home/ukas/surface-aggregator-module/scripts/ssam/libssam.py", line 350, in request
    return _request(self.fd, request)
  File "/home/ukas/surface-aggregator-module/scripts/ssam/libssam.py", line 258, in _request
    raise OSError(-raw.status, errno.errorcode.get(-raw.status))
TimeoutError: [Errno 110] ETIMEDOUT

sudo ./scripts/ssam/ctrl.py request 2 2 1 1 1
Traceback (most recent call last):
  File "/home/ukas/surface-aggregator-module/./scripts/ssam/ctrl.py", line 49, in <module>
    main()
  File "/home/ukas/surface-aggregator-module/./scripts/ssam/ctrl.py", line 43, in main
    rsp = ctrl.request(rqst)
  File "/home/ukas/surface-aggregator-module/scripts/ssam/libssam.py", line 350, in request
    return _request(self.fd, request)
  File "/home/ukas/surface-aggregator-module/scripts/ssam/libssam.py", line 258, in _request
    raise OSError(-raw.status, errno.errorcode.get(-raw.status))
TimeoutError: [Errno 110] ETIMEDOUT

**Comment by qzed** [comment]
Okay, so the output for the `hid` commands is a bit troubling, so if I didn't screw up with the commands that suggests that there might be a new interface. Are you sure that all of them time out? Could you also try the following commands?

```
sudo ./scripts/ssam/hid.py hid-get-descriptor 0 1
sudo ./scripts/ssam/hid.py hid-get-descriptor 1 0
```

For the battery commands, this indicates that the interface hasn't changed (the two timeouts there are expected).

**Comment by qzed** [comment]
Oh and if you press any keys on the keyboard or touch the touchpad, is there any output to the dmesg log?

**Comment by ukasuviok** [comment]
> Oh and if you press any keys on the keyboard or touch the touchpad, is there any output to the dmesg log?

A lot of these.
[ 1354.311656] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.318990] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.326773] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.334105] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.341225] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.348413] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.355567] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.362999] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.370666] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.377986] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.385310] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.392634] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.399526] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.407049] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.414253] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.421943] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.429331] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.436626] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)
[ 1354.443214] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x03)

**Comment by qzed** [comment]
Ahh, there we go. Okay, so it looks like the `tid` changed from `0x02` to `0x01`. Give me a sec and I'll update the script.

**Comment by qzed** [comment]
Thanks! There's a lot more than I expected. I'll translate that and if all goes well you can expect keyboard, touchpad and battery support in the next release.

**Comment by ukasuviok** [comment]
Thanks!  I appreciate all of your help.

**Comment by qzed** [comment]
Since there are quite many HID devices in comparison to other devices, can you try running `sudo ./scripts/ssam/hid.py hid-get-descriptor 1 <iid> 1` with `<iid>` from `10` to `20` and see if there's any output there? Just to check that we aren't missing anything.

Also if you have a slim-pen can you try to remove and re-stash the pen? That should produce some `unhandled event` messages in the dmesg log. Can you check what the `iid` (last number) is for those? I assume this should be `0x02` based on the descriptors.

Lastly, I assume touching the touchscreen doesn't emit any `unhandled event` messages?

**Comment by qzed** [comment]
Perfect, thanks!

**Comment by qzed** [comment]
Okay, https://github.com/linux-surface/kernel/commit/2452f61c9351c791e56ba5c187d26ad797530fed should add support for all of this. I'll start some new kernel builds next. It will probably take two hours or so until they are available.

**Comment by ukasuviok** [comment]
Will an apt-get upgrade catch this or will it need to be built manually?

**Comment by ukasuviok** [comment]
I can wait. Thanks again.

Steve Dixon

**Comment by qzed** [comment]
New releases are now available (v5.14.10-3). Can you check if battery information is now available and the touchpad and keyboard work?

Can you also use the `surface` tool (from the `surface-control` package) to check if switching performance modes / platform profiles work via `surface profile set <profile>` where `<profile>` is one of the profiles listed in `surface profile list`. After that, `surface profile get` should return the profile you've just set (maybe do that a couple of times with different profiles to make sure).

**Comment by qzed** [comment]
Ah and there's another thing that we should check (forgot that yesterday): Since the target ID changed, it's possible that the command used for enabling/disabling events also changed. To do that run

```sh
./scripts/ssam/evreg.py reg-disable 0x15 0x00 0x03
```

This should disable the touchpad. If the touchpad didn't work before (e.g. due to old kernel), it should stop emitting any `unhandled event` messages in the dmesg log. Running

```sh
./scripts/ssam/evreg.py reg-enable 0x15 0x00 0x03
```

should enable it again. Can you make sure that this is the case?

**Comment by qzed** [comment]
Yeah okay, so that has changed as well. Can you change these lines in the `evreg.py` script (https://github.com/linux-surface/surface-aggregator-module/blob/a33c002fa5fb7a1468f14148dd54da0624ac394d/scripts/ssam/evreg.py#L14-L15), specifically `'tid': 2` to `'tid': 1` and try again?

If that doesn't work, can you try both
```
./scripts/ssam/evreg.py kip-disable 0x15 0x00 0x03
./scripts/ssam/evreg.py sam-disable 0x15 0x00 0x03
```
and see if any of that works (especially disables the `unhandled event` messages for the touchpad/the touchpad itself)? If the `kip` command times out, can you try changing the `tid` for that from 2 to 1 as well (https://github.com/linux-surface/surface-aggregator-module/blob/a33c002fa5fb7a1468f14148dd54da0624ac394d/scripts/ssam/evreg.py#L12-L13)?

**Comment by qzed** [comment]
Okay, that looks good so far. Does it have any effect on the touchpad events?

**Comment by qzed** [comment]
@ukasuviok New kernels are available now. Can you check if battery status, keyboard, touchpad, and platform profiles work with that?

**Comment by qzed** [comment]
Hmm okay, can you post a dmesg log and the output of `ls -al /sys/bus/surface_aggregator/devices`?

**Comment by qzed** [comment]
Ahh I forgot to update the line matching the device to the driver... that still only has target ID 2, but should naturally load against 1 and 2. You could try binding the driver manually. I think that should work (not entirely sure though). To do that run:

```
sudo modprobe surface_hid
echo 01:15:01:01:00 | sudo tee /sys/bus/surface_aggregator/drivers/surface_hid/bind
echo 01:15:01:03:00 | sudo tee /sys/bus/surface_aggregator/drivers/surface_hid/bind
```

That should hopefully get the keyboard and touchpad working.

**Comment by qzed** [comment]
> ```
> echo 01:15:01:01:00 | sudo tee /sys/bus/surface_aggregator/drivers/surface_hid/bind
> 01:15:01:01:00
> tee: /sys/bus/surface_aggregator/drivers/surface_hid/bind: No such device
> ```

Ah yeah okay then the match line blocks this. Anyway, I've triggered a new build. So hopefully this time it works.

> Also, I currently have he power profile set to low-power, but the laptop is still pretty warm and the fans are running.

As far as I can tell, that profile mostly influences the cooling behavior (i.e. fan curve). You could try to figure out if there's something consuming a lot of CPU. If you've got a model with the discrete GPU you probably want to make sure that runtime PM is on for that (on my SB2 that also got decently warm just by idling) and that it's not used to render the desktop. You can check temperatures of the dGPU via `nvidia-smi` (if you've got the nvidia driver installed). There's some info on runtime PM here: https://github.com/linux-surface/surface-hotplug/wiki/Runtime-Power-Management.

**Comment by qzed** [comment]
Something else to check: Are there any `unhandled event` messages when you move the screen into different positions (e.g. switch between tablet mode and laptop mode)? Linux supports a `SW_TABLET_MODE` input event, would be good if we can add support for that as well (that allows e.g. Gnome to decide when to display the onscreen keyboard).

**Comment by ukasuviok** [comment]
Yes it does.

Tent/Tablet mode
[  228.686478] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  228.785235] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  228.885277] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  228.985273] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  229.085281] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  229.184025] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  229.283585] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  229.382200] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  229.482278] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)

Back to Laptop mode
[  305.701958] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  305.800953] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  305.901276] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  306.000738] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  306.099793] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  306.199890] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  306.298957] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  306.397607] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)
[  306.496649] surface_serial_hub serial0-0: event: unhandled event (rqid: 0x15, tc: 0x15, tid: 0x01, cid: 0x00, iid: 0x01)

Also that's for the dGPU info.  I disabled it and can already feel a difference heat wise and see a difference in the battery monitor.

**Comment by qzed** [comment]
> Yes it does.

Okay, that looks like normal HID events from the keyboard device. Could be that that that's implemented that way. Might be worth to check the specific events being reported via evtest or hid-recorder something like that once the HID devices work.

> Also thanks for the dGPU info. I disabled it and can already feel a difference heat wise and see a difference in the battery monitor.

Nice! Yeah the dGPU is a bit of a power hog. Best to keep that disabled until you actually need it or configure it so that it can go into low power mode (the last couple of driver updates from nvidia seem to have improved things, especially with `NVreg_DynamicPowerManagement=0x02`).

**Comment by qzed** [comment]
Oh and if the keyboard should work this time, can you make sure that it still works after switching to tablet mode and back?

**Comment by qzed** [comment]
Okay, can you post a dmesg log?

**Comment by qzed** [comment]
Are there any `unhandled event` messages when using the touchpad? As far as I can tell from the log, the HID device gets created just fine.

**Comment by ukasuviok** [comment]
There are no unhandled events.  I did notice that the trackpad does work for clicks, but there's nothing for any sort of movement.

**Comment by qzed** [comment]
I wonder if that has something to do with their new haptic touchpad... from what I can tell it should receive HID events, but it's possible that either the kernel doesn't know what to do with them or needs to send some sort of enable-command back to the device (that's e.g. necessary for normal MS precision touchpads, which work in single-finger mouse-mode only until then).

Can you try and play around with `hid-recorder` and `evtest` a bit and see what they return as events. You might need to find the correct device first as it creates 4 HID sub-devices (Mouse, Touchpad, and 2 unknowns).

**Comment by ukasuviok** [comment]
That fixed it.  How exactly do I use hid-recorder.  It gives me a list of devices I can choose.  After I choose one it prints out some device information.  I have to CTRL+C out of the program to get my terminal back.  Is there a way I should be saving the output of each device?

**Comment by qzed** [comment]
Once you've found the device you can run `sudo hidrecorder /dev/hidrawX > output.log` (where `X` is the device number). That should create a log file. You could also just try running it for a bit without redirecting the output and see if it reacts to touch input. If it does you can also just post an excerpt of that.

**Comment by qzed** [comment]
> FYI: it looks like the sensors are working. I had to turn the auto-brightness off because it was driving me crazy.

Heh, that's auto-brightness on Linux...

> Also, the function/media keys on they keyboard work too.

Nice! Thanks for the feedback.

**Comment by ukasuviok** [comment]
[output.log](https://github.com/linux-surface/linux-surface/files/7318480/output.log)
Output from /dev/hidraw4 is attached.

**Comment by qzed** [comment]
Okay, that doesn't look like anything special, i.e. looks pretty much like your standard Microsoft Precision touchpad (with some additional data).

Here's an example report showing two fingers:
```sh
E: 000001.586497 44 04 03 d0 02 cf 02 7d 01 07 71 03 9b 01 7d 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 13 93 02 01 7d 01 63 1f
# ReportID: 4 / Confidence: 1 | Tip Switch: 1 | Contact Id:  0 | # | X:    704 | Y:    693 | Tip Pressure:    384
#             | Confidence: 1 | Tip Switch: 1 | Contact Id:  1 | # | X:    862 | Y:    378 | Tip Pressure:    384
#             | Confidence: 0 | Tip Switch: 0 | Contact Id:  0 | # | X:      0 | Y:      0 | Tip Pressure:      0
#             | Confidence: 0 | Tip Switch: 0 | Contact Id:  0 | # | X:      0 | Y:      0 | Tip Pressure:      0
#             | Confidence: 0 | Tip Switch: 0 | Contact Id:  0 | # | X:      0 | Y:      0 | Tip Pressure:      0 | Scan Time:  37723 | Contact Count:    2 | Button: 1 | # | 0xf     f010001:  125 | 0xff010002:    1 | 0xff010003:   8040
```

And here's a similar example from my Surface Book 2:
```sh
E: 000006.346933 30 04 03 ca 03 31 02 07 96 04 6e 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 03 59 02 00
# ReportID: 4 / Confidence: 1 | Tip Switch: 1 | Contact Id:  0 | # | X:    970 | Y:    561
#             | Confidence: 1 | Tip Switch: 1 | Contact Id:  1 | # | X:   1174 | Y:    366
#             | Confidence: 0 | Tip Switch: 0 | Contact Id:  0 | # | X:      0 | Y:      0
#             | Confidence: 0 | Tip Switch: 0 | Contact Id:  0 | # | X:      0 | Y:      0
#             | Confidence: 0 | Tip Switch: 0 | Contact Id:  0 | # | X:      0 | Y:      0 | Scan Time:  22858 | Contact Count:    2 | Button: 0 | #
```

There are two differences:
1. The `Tip Pressure` field.
2. The extended information: `0xf     f010001:  125 | 0xff010002:    1 | 0xff010003:   8040`

So looks like maybe something in the input pipeline isn't happy with one of the additional fields? Can you try running `evtest` (similar command scheme) and figure out if that is able to capture any input events? If that doesn't report any events, the data is lost somewhere in the HID to kernel input event translation. If that does report events, it's something in user-space.

Also does `journalctl -b -e` show any notable warnings or errors?

**Comment by ukasuviok** [comment]
I'm not sure if this is important or not, but it's from journalctl.

Oct 10 18:48:13 ukas-lt11u gnome-shell[1554]: libinput error: event12 - Microsoft Surface 045E:09AF Touchpad: kernel bug: Touch jump detected and discarded.
Oct 10 18:48:13 ukas-lt11u gnome-shell[1554]: See https://wayland.freedesktop.org/libinput/doc/1.16.4/touchpad-jumping-cursors.html for details
Oct 10 18:48:14 ukas-lt11u gnome-shell[1554]: libinput error: event12 - Microsoft Surface 045E:09AF Touchpad: kernel bug: Touch jump detected and discarded.
Oct 10 18:48:14 ukas-lt11u gnome-shell[1554]: See https://wayland.freedesktop.org/libinput/doc/1.16.4/touchpad-jumping-cursors.html for details
Oct 10 18:48:14 ukas-lt11u gnome-shell[1554]: libinput error: event12 - Microsoft Surface 045E:09AF Touchpad: kernel bug: Touch jump detected and discarded.
Oct 10 18:48:14 ukas-lt11u gnome-shell[1554]: See https://wayland.freedesktop.org/libinput/doc/1.16.4/touchpad-jumping-cursors.html for details
Oct 10 18:48:14 ukas-lt11u gnome-shell[1554]: libinput error: event12 - Microsoft Surface 045E:09AF Touchpad: kernel bug: Touch jump detected and discarded.
Oct 10 18:48:14 ukas-lt11u gnome-shell[1554]: See https://wayland.freedesktop.org/libinput/doc/1.16.4/touchpad-jumping-cursors.html for details
Oct 10 18:48:14 ukas-lt11u gnome-shell[1554]: libinput error: event12 - Microsoft Surface 045E:09AF Touchpad: kernel bug: Touch jump detected and discarded.
Oct 10 18:48:14 ukas-lt11u gnome-shell[1554]: See https://wayland.freedesktop.org/libinput/doc/1.16.4/touchpad-jumping-cursors.html for details
Oct 10 18:48:14 ukas-lt11u gnome-shell[1554]: libinput error: event12 - Microsoft Surface 045E:09AF Touchpad: WARNING: log rate limit exceeded (5 msgs per 2h). Discarding future messages.

**Comment by qzed** [comment]
Okay, I can't find any way to disable that without having to re-build libinput... I also don't really understand why that check triggers as the deltas seem reasonable. Unfortunately, libinput is something that I don't know much of. So you should probably head over to https://gitlab.freedesktop.org/libinput/libinput and open up an issue there (see https://wayland.freedesktop.org/libinput/doc/latest/reporting-bugs.html for details).

From the kernel side I think everything works as expected. User-space does see the events (as verified via evtest) and the reported events look reasonable (although I'm not an expert on that).

**Comment by ukasuviok** [comment]
I'm not sure what I should tell them regarding the bug report.

**Comment by ukasuviok** [comment]
Great!

**Comment by qzed** [comment]
Okay, so can you try adding the following to `/etc/libinput/local-overrides.quirks`:

```
[Microsoft Surface Laptop Studio Touchpad]
MatchName=*Microsoft Surface 045E:09AF Touchpad*
ModelLenovoX1Gen6Touchpad=1
```

Then to verify run `libinput quirks list /dev/input/eventX` where `X` is the number of the input device (e.g. from `evtest` or `libinput record`). That should then show the `ModelLenovoX1Gen6Touchpad=1` entry.

**Comment by ukasuviok** [comment]
Should I be concerned that there is no /etc/libinput directory or just go ahead and create it?

**Comment by qzed** [comment]
I think you can just create it. I got that directory from https://wayland.freedesktop.org/libinput/doc/latest/device-quirks.html#installing-temporary-local-device-quirks which mentions that that file normally doesn't exist.

**Comment by qzed** [comment]
I wonder if `event12 - palm: touch 0 (TOUCH_HOVERING), palm detected (pressure)` means that palm detection triggers erroneously on fingers. That seems to be configurable: https://wayland.freedesktop.org/libinput/doc/latest/touchpad-pressure-debugging.html#touchpad-pressure-hwdb. If I read that right, the idea is to use `sudo libinput measure touchpad-pressure` to figure out touch and palm thresholds and then set them in the device quirks accordingly.

**Comment by qzed** [comment]
Seems like a lot of those get detected as palm. Maybe try something like
```
sudo libinput measure touchpad-pressure --touch-thresholds=10:0 --palm-threshold=500
```
and check if that leads to better results.

**Comment by ukasuviok** [comment]
That actually seems to have done the trick.  Thank you for all of the help with getting everything working.  Microsoft always has to make things complicated.

**Comment by qzed** [comment]
Awesome! You should probably try to remove the `ModelLenovoX1Gen6Touchpad=1` quirk now and see if that works without it. I guess that might just have been some combination resulting from the palm detection going wrong.

After that you should report those values to libinput so that they can add this to their hardware database.

**Comment by ukasuviok** [comment]
Not that I could see when I was checking last night.

Steve Dixon

**Comment by qzed** [comment]
Closing this. Keyboard, touchpad, and battery stats work and for everything else you should probably open up a new separate issue. I'll try to find some time to re-work the patches a bit and then send them upstream.
